### PR TITLE
Add sendDebug method, debug event and test

### PR DESCRIPTION
**Pull request by barbagrigia**
[Logux debug](http://cultofmartians.com/tasks/logux-debug.html)

### CODE REVIEW

**Comment by ai** [comment]
Why do you need magic:

```js
  sendDebug: function sendDebug () {
    var type = arguments[0]
    var data = arguments[1]
```

Just write:

```js
  sendDebug: function sendDebug (type, data) {
```

It will be 100% same.

**Comment by ai** [comment]
Let’s also check in validator `data` type on `type === "error"`

**Comment by ai** [comment]
`test.leftEvents` in test is not a emitted from server. It is events emitted from `Connection`. So you need to manually grab emits:

```js
var fired = []
test.lestSync.on('debug', (type, data) => {
  fired.push(type, data)
})
```

**Comment by barbagrigia** [comment]
> Let’s also check in validator data type on type === "error"

But if in the future will be added new types?

**Comment by ai** [comment]
> But if in the future will be added new types?

Your are right. So let's check `data` type *only* on `error`.

**Comment by barbagrigia** [comment]
> Your are right. So let's check data type only on error.

But `data` can be any type...

**Comment by ai** [comment]
@barbagrigia for `type === "error"` `data` could be only string with stacktrace.

Of course, if `type !== "error"` it could be any type in the future.

**Comment by barbagrigia** [comment]
> `test.leftEvents` in test is not a emitted from server. It is events emitted from `Connection`.

Clarify the [task](http://cultofmartians.com/tasks/logux-debug.html): 

> 4. ... and `debug` event when receiving a command...

`debug` event should be emitted from the server or when receiving a command ?

**Comment by ai** [comment]
In `test.leftEvents` you check that event was sent, not that it was received by server and server emit event.

Sync should emit `debug` event, when he received `["debug", type, data]`

**Comment by ai** [comment]
Do not merge commit in pull request. Always do rebase.Here is how to fix:

```sh
git reset HEAD^
git checkout master
git pull git@github.com:logux/logux-sync.git master
git checkout debug-command
git rebase master
```

**Comment by ai** [comment]
@barbagrigia please remove that `merge` commit and made rebase ;)

**Comment by ai** [comment]
Please, remove `revert` commits, make rebase and do force push:

```sh
git reset HEAD^^^^
# commit your chages again (manually remove changes from merge)
git checkout master
git pull git@github.com:logux/logux-sync.git master
git checkout debug-command
git rebase master
git push origin debug-command --force
```

Force push is good thing in pull requests. In big open source projects, merge commits are prohibited. It is good time to practice git skills.

**Comment by barbagrigia** [comment]
Can I reopen PR ?

**Comment by ai** [comment]
Looks good. I will accept it when I will be home.

Thanks for work 👍

**Comment by barbagrigia** [comment]
👌

**Comment by ai** [comment]
I merged it. And updated version in Logux Server. I am waiting for next PR.

**Pull request merged**
